spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/unbound
    username: postgres
    password: project123
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    show-sql: true
  application:
    name: oauthserver-service
  profiles:
    active: dev

server:
  port: 9100

eureka:
  client:
    register-with-eureka: true
    fetch-registry: false
    service-url:
      defaultZone: http://apimanager:8000/eureka
  instance:
    leaseRenewalIntervalInSeconds: 5   
    preferIpAddress: true

security:
  values:
    secret: Prueba
    ttl: 3600